### ISSUE TITLE
Make neon npm-installable

### ISSUE THREAD

**Issue by chrislong** [NextCenturyCorporation/neon#12]
For building apps based on Neon, it would be nice if it could be installed with npm.

**Comment by lmizenextcen** [comment]
How much are you looking to be installed with npm?  It should be simple enough to bundle the build artifacts (neon.war, neon.js, neon-nodeps.js) together in an npm module.  However, the Neon WAR file is typically installed under a Tomcat instance or equivalent web container.  Once the artifacts are pulled via NPM, it may be preferable to deploy the installed war file via another npm package like grunt-tomcat-deploy or node-tomcat-deploy.

**Comment by lmizenextcen** [comment]
I'm adding this as part of a general clean up of the neon.js dependencies.  So when it goes to npm, it won't require jquery 1 or some ancient version of lodash.

**Comment by lmizenextcen** [comment]
Recent stable builds have been pushed to [Neon Framework](https://www.npmjs.com/package/neon-framework).
