### ISSUE TITLE
exception: can't convert from BSON type String to Date

### ISSUE THREAD

**Issue by trustdarkness** [NextCenturyCorporation/neon#6]
I'm running this from git on Debian Jessie.  Heatmap works fine, but the other visual graphs in the angular demo do not (using the earthquake sample data).  The traceback I get from the jettyRun process is below.

2014-07-25 16:21:10 com.ncc.neon.services.GenericExceptionMapper ERROR - { "serverUsed" : "localhost/127.0.0.1:27017" , "err
msg" : "exception: can't convert from BSON type String to Date" , "code" : 16006 , "ok" : 0.0}
com.mongodb.CommandFailureException: { "serverUsed" : "localhost/127.0.0.1:27017" , "errmsg" : "exception: can't convert fro
m BSON type String to Date" , "code" : 16006 , "ok" : 0.0}
# java -version

java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-2)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
# nodejs -v

v0.10.29
# npm -v

1.4.4

**Comment by ScorpioT1000** [comment]
This error also occurs when you missing $ symbol in the field name:

Wrong:

    month: { '$month': 'created_at' }

Right:

    month: { '$month': '$created_at' }
