### ISSUE TITLE
Links to API docs for both eventing and query from documentation wiki are showing 0.9.0

### ISSUE THREAD

**Issue by colemanserious** [NextCenturyCorporation/neon#8]
Looks like the baseURL for the docs have changed between 0.9.0 and 1.1.0-SNAPSHOT..  The links from the neonframework.org Documentation dropdown link to latest; the links from the Documentation wiki link to 0.9.0.

BaseURL for 1.1.0-SNAPSHOT (e.g., latest) = http://neonframework.org/neon/apidocs/latest/jsdocs
BaseURL for 0.9.0 (not latest): http://neonframework.org/apidocs/latest/jsdocs/

**Comment by lmizenextcen** [comment]
Thanks for the catch.  The links on the wiki now match the neonframework.org links.  If you see any others we missed, let us know.
